spring:
  config:
    import:
      - optional:classpath:./application-auth.yml
  datasource:
    url: jdbc:mysql://localhost:3306/dnd10
    username: dnd10user
    password: dnd10user
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect