spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dnd10
    username: dnd10user
    password: dnd10user
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect